// src/views/Profile.vue
<template>
  <AppLayout>
    <div class="container mx-auto max-w-[700px] px-4 py-12">
      <div class="mb-8 text-center">
        <h1 class="text-2xl font-bold md:text-3xl">{{ t.profile.title }}</h1>
        <p class="mt-2 text-muted-foreground">{{ t.profile.subtitle }}</p>
      </div>

      <div class="flex flex-col gap-6">
        <div class="rounded-xl border border-border bg-card p-6">
          <div class="mb-1 flex items-center gap-2">
            <User class="h-5 w-5" />
            <h2 class="text-lg font-semibold">{{ t.profile.accountInfo }}</h2>
          </div>
          <p class="mb-4 text-sm text-muted-foreground">{{ t.profile.accountInfoDesc }}</p>
          <div class="grid gap-4 sm:grid-cols-2">
            <div>
              <p class="text-xs text-muted-foreground">{{ t.profile.fullName }}</p>
              <p class="font-medium">{{ mockUser.fullName }}</p>
            </div>
            <div>
              <p class="text-xs text-muted-foreground">{{ t.profile.email }}</p>
              <p class="font-medium">{{ mockUser.email }}</p>
            </div>
          </div>
        </div>

        <div class="rounded-xl border border-border bg-card p-6">
          <div class="mb-1 flex items-center gap-2">
            <Lock class="h-5 w-5" />
            <h2 class="text-lg font-semibold">{{ t.profile.changePassword }}</h2>
          </div>
          <p class="mb-4 text-sm text-muted-foreground">{{ t.profile.changePasswordDesc }}</p>

          <form @submit.prevent="handleChangePassword" class="space-y-4">
            <div v-if="error" class="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">
              {{ error }}
            </div>
            <div v-if="success" class="flex items-center gap-2 rounded-lg bg-primary/10 p-3 text-sm text-primary">
              <Check class="h-4 w-4" />
              {{ t.profile.successMessage }}
            </div>

            <div class="space-y-2">
              <label for="current-pw" class="text-sm font-medium">{{ t.profile.currentPassword }}</label>
              <div class="relative">
                <input
                  id="current-pw"
                  v-model="currentPassword"
                  :type="showCurrent ? 'text' : 'password'"
                  class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 pr-9 text-sm shadow-xs outline-none focus-visible:ring-2 focus-visible:ring-ring"
                  :placeholder="t.profile.currentPasswordPlaceholder"
                />
                <button
                  type="button"
                  class="absolute right-2 top-1/2 -translate-y-1/2 rounded p-1.5 text-muted-foreground hover:bg-accent"
                  @click="showCurrent = !showCurrent"
                >
                  <Eye v-if="!showCurrent" class="h-4 w-4" />
                  <EyeOff v-else class="h-4 w-4" />
                </button>
              </div>
            </div>
            <div class="space-y-2">
              <label for="new-pw" class="text-sm font-medium">{{ t.profile.newPassword }}</label>
              <div class="relative">
                <input
                  id="new-pw"
                  v-model="newPassword"
                  :type="showNew ? 'text' : 'password'"
                  class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 pr-9 text-sm shadow-xs outline-none focus-visible:ring-2 focus-visible:ring-ring"
                  :placeholder="t.profile.newPasswordPlaceholder"
                />
                <button
                  type="button"
                  class="absolute right-2 top-1/2 -translate-y-1/2 rounded p-1.5 text-muted-foreground hover:bg-accent"
                  @click="showNew = !showNew"
                >
                  <Eye v-if="!showNew" class="h-4 w-4" />
                  <EyeOff v-else class="h-4 w-4" />
                </button>
              </div>
            </div>
            <div class="space-y-2">
              <label for="confirm-pw" class="text-sm font-medium">{{ t.profile.confirmNewPassword }}</label>
              <div class="relative">
                <input
                  id="confirm-pw"
                  v-model="confirmPassword"
                  :type="showConfirm ? 'text' : 'password'"
                  class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 pr-9 text-sm shadow-xs outline-none focus-visible:ring-2 focus-visible:ring-ring"
                  :placeholder="t.profile.confirmNewPasswordPlaceholder"
                />
                <button
                  type="button"
                  class="absolute right-2 top-1/2 -translate-y-1/2 rounded p-1.5 text-muted-foreground hover:bg-accent"
                  @click="showConfirm = !showConfirm"
                >
                  <Eye v-if="!showConfirm" class="h-4 w-4" />
                  <EyeOff v-else class="h-4 w-4" />
                </button>
              </div>
            </div>

            <button
              type="submit"
              class="inline-flex h-10 w-full items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 disabled:opacity-50"
              :disabled="loading"
            >
              <span v-if="loading" class="mr-2 h-4 w-4 animate-spin rounded-full border-2 border-primary-foreground border-t-transparent" />
              {{ loading ? t.profile.updating : t.profile.updatePassword }}
            </button>
          </form>
        </div>
      </div>
    </div>
  </AppLayout>
</template>

<script setup>
import { ref } from 'vue'
import { User, Lock, Check, Eye, EyeOff } from 'lucide-vue-next'
import AppLayout from '@/components/AppLayout.vue'
import { useLanguage } from '@/composables/useLanguage'

const { t } = useLanguage()

const mockUser = {
  email: 'user@example.com',
  fullName: 'John Doe',
}

const currentPassword = ref('')
const newPassword = ref('')
const confirmPassword = ref('')
const showCurrent = ref(false)
const showNew = ref(false)
const showConfirm = ref(false)
const loading = ref(false)
const error = ref('')
const success = ref(false)

const handleChangePassword = async () => {
  if (!currentPassword.value || !newPassword.value || !confirmPassword.value) return
  if (newPassword.value.length < 8) {
    error.value = t.profile.passwordMinLength
    return
  }
  if (newPassword.value !== confirmPassword.value) {
    error.value = t.profile.passwordsNoMatch
    return
  }

  error.value = ''
  success.value = false
  loading.value = true

  await new Promise((r) => setTimeout(r, 1000))

  loading.value = false
  success.value = true
  currentPassword.value = ''
  newPassword.value = ''
  confirmPassword.value = ''
  setTimeout(() => (success.value = false), 3000)
}
</script>

// ui/app/profile/page.tsx
"use client"

import React from "react"
import { useState } from "react"
import { AppLayout } from "@/components/app-layout"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { User, Lock, Eye, EyeOff, Check } from "lucide-react"
import { useLanguage } from "@/components/language-provider"

// Mock user data - in production this would come from Supabase auth
const mockUser = {
  email: "user@example.com",
  fullName: "John Doe",
}

export default function ProfilePage() {
  const { t } = useLanguage()
  const [currentPassword, setCurrentPassword] = useState("")
  const [newPassword, setNewPassword] = useState("")
  const [confirmPassword, setConfirmPassword] = useState("")
  const [showCurrentPassword, setShowCurrentPassword] = useState(false)
  const [showNewPassword, setShowNewPassword] = useState(false)
  const [showConfirmPassword, setShowConfirmPassword] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const [success, setSuccess] = useState(false)
  const [error, setError] = useState("")

  const handleChangePassword = async (e: React.FormEvent) => {
    e.preventDefault()
    setError("")
    setSuccess(false)

    if (newPassword !== confirmPassword) {
      setError(t.profile.passwordsNoMatch)
      return
    }

    if (newPassword.length < 8) {
      setError(t.profile.passwordMinLength)
      return
    }

    setIsLoading(true)

    // Mock password change - in production this would call Supabase
    await new Promise((resolve) => setTimeout(resolve, 1000))

    setIsLoading(false)
    setSuccess(true)
    setCurrentPassword("")
    setNewPassword("")
    setConfirmPassword("")

    // Clear success message after 3 seconds
    setTimeout(() => setSuccess(false), 3000)
  }

  return (
    <AppLayout>
      <div className="container mx-auto px-4 py-12">
        <div className="mx-auto max-w-2xl space-y-8">
          <div className="text-center">
            <h1 className="text-3xl font-bold text-foreground">{t.profile.title}</h1>
            <p className="mt-2 text-muted-foreground">
              {t.profile.subtitle}
            </p>
          </div>

          {/* User Info Card */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <User className="h-5 w-5" />
                {t.profile.accountInfo}
              </CardTitle>
              <CardDescription>{t.profile.accountInfoDesc}</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid gap-4 sm:grid-cols-2">
                <div>
                  <Label className="text-muted-foreground">{t.profile.fullName}</Label>
                  <p className="mt-1 font-medium text-foreground">{mockUser.fullName}</p>
                </div>
                <div>
                  <Label className="text-muted-foreground">{t.profile.email}</Label>
                  <p className="mt-1 font-medium text-foreground">{mockUser.email}</p>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Change Password Card */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Lock className="h-5 w-5" />
                {t.profile.changePassword}
              </CardTitle>
              <CardDescription>
                {t.profile.changePasswordDesc}
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleChangePassword} className="space-y-4">
                {error && (
                  <div className="rounded-lg border border-destructive/50 bg-destructive/10 p-3 text-sm text-destructive">
                    {error}
                  </div>
                )}

                {success && (
                  <div className="flex items-center gap-2 rounded-lg border border-green-500/50 bg-green-500/10 p-3 text-sm text-green-600 dark:text-green-400">
                    <Check className="h-4 w-4" />
                    {t.profile.successMessage}
                  </div>
                )}

                <div className="space-y-2">
                  <Label htmlFor="currentPassword">{t.profile.currentPassword}</Label>
                  <div className="relative">
                    <Input
                      id="currentPassword"
                      type={showCurrentPassword ? "text" : "password"}
                      value={currentPassword}
                      onChange={(e) => setCurrentPassword(e.target.value)}
                      placeholder={t.profile.currentPasswordPlaceholder}
                      required
                    />
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="absolute right-0 top-0 h-full px-3 hover:bg-transparent"
                      onClick={() => setShowCurrentPassword(!showCurrentPassword)}
                    >
                      {showCurrentPassword ? (
                        <EyeOff className="h-4 w-4 text-muted-foreground" />
                      ) : (
                        <Eye className="h-4 w-4 text-muted-foreground" />
                      )}
                    </Button>
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="newPassword">{t.profile.newPassword}</Label>
                  <div className="relative">
                    <Input
                      id="newPassword"
                      type={showNewPassword ? "text" : "password"}
                      value={newPassword}
                      onChange={(e) => setNewPassword(e.target.value)}
                      placeholder={t.profile.newPasswordPlaceholder}
                      required
                    />
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="absolute right-0 top-0 h-full px-3 hover:bg-transparent"
                      onClick={() => setShowNewPassword(!showNewPassword)}
                    >
                      {showNewPassword ? (
                        <EyeOff className="h-4 w-4 text-muted-foreground" />
                      ) : (
                        <Eye className="h-4 w-4 text-muted-foreground" />
                      )}
                    </Button>
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="confirmPassword">{t.profile.confirmNewPassword}</Label>
                  <div className="relative">
                    <Input
                      id="confirmPassword"
                      type={showConfirmPassword ? "text" : "password"}
                      value={confirmPassword}
                      onChange={(e) => setConfirmPassword(e.target.value)}
                      placeholder={t.profile.confirmNewPasswordPlaceholder}
                      required
                    />
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="absolute right-0 top-0 h-full px-3 hover:bg-transparent"
                      onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                    >
                      {showConfirmPassword ? (
                        <EyeOff className="h-4 w-4 text-muted-foreground" />
                      ) : (
                        <Eye className="h-4 w-4 text-muted-foreground" />
                      )}
                    </Button>
                  </div>
                </div>

                <Button type="submit" className="w-full" disabled={isLoading}>
                  {isLoading ? t.profile.updating : t.profile.updatePassword}
                </Button>
              </form>
            </CardContent>
          </Card>
        </div>
      </div>
    </AppLayout>
  )
}
